language: python
python:
  - "3.4"
before_install:
  - export DJANGO_SETTINGS_MODULE=example_base.dev_test
# command to install dependencies
install:
  - pip install -r requirements/ci.txt
# command to run tests
script: py.test
